export const brands = [
  { name: "A-COLD-WALL*", image: "/brands/a_cold_wall.jpg" },
  { name: "about:blank", image: "/brands/about_blank.jpg" },
  { name: "Acne Studios", image: "/brands/acne_studios.jpg" },
  { name: "adidas", image: "/brands/adidas.jpg" },
  { name: "AllSaints", image: "/brands/all_saints.jpg" },
  { name: "Balenciaga", image: "/brands/balenciaga.jpg" },
  { name: "Balmain", image: "/brands/balmain.jpg" },
  { name: "Burberry", image: "/brands/burberry.jpg" },
  { name: "Calvin Klein", image: "/brands/calvin_klein.jpg" },
  { name: "Comme des Garçons", image: "/brands/comme_des_garcons.jpg" },
  { name: "Dior", image: "/brands/dior.jpg" },
  { name: "Disturbia", image: "/brands/disturbia.jpg" },
  { name: "Drop Dead", image: "/brands/drop_dead.jpg" },
  { name: "Dsquared2", image: "/brands/dsquared2.jpg" },
  { name: "Essentials", image: "/brands/essentials.jpg" },
  { name: "Fear Of God", image: "/brands/fear_of_god.jpg" },
  { name: "Gucci", image: "/brands/gucci.jpg" },
  { name: "Humanrace", image: "/brands/humanrace.jpg" },
  { name: "Issey Miyake", image: "/brands/issey_miyake.jpg" },
  { name: "Loewe", image: "/brands/loewe.jpg" },
  { name: "Maison Kitsuné", image: "/brands/maison_kitsune.jpg" },
  { name: "Naked Wolfe", image: "/brands/naked_wolfe.jpg" },
  { name: "Nike", image: "/brands/nike.jpg" },
  { name: "Off-White", image: "/brands/off_white.jpg" },
  { name: "Palm Angels", image: "/brands/palm_angels.jpg" },
  { name: "Prada", image: "/brands/prada.jpg" },
  { name: "Represent", image: "/brands/represent.jpg" },
  { name: "Rick Owens", image: "/brands/rick_owens.jpg" },
  { name: "Vans", image: "/brands/vans.jpg" },
];
